services:
  database:
    image: postgres:14
    container_name: todo-database
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - todo:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

volumes:
  todo:
